server:
  port: 9999
github:
 client:
  id : 3c283c1af5eacb29e46a
  secret : 318bf03ce81e7baadaf3d8887ca660e02d6af8a9
 redirect:
   url : http://localhost:9999/callback

#数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newpool_practice?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#### mybatis 驼峰命名赋值
mybatis:
  configuration:
    map-underscore-to-camel-case: true

